//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Enclosing_Operation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Enclosing_Operation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="Overridden_Fixed_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Overridden_Fixed_Priority"/>
 *           &lt;element name="Overridden_Permanent_FP" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Overridden_Permanent_FP"/>
 *         &lt;/choice>
 *         &lt;element name="Operation_List" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref_List"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier" />
 *       &lt;attribute name="Worst_Case_Execution_Time" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Average_Case_Execution_Time" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Best_Case_Execution_Time" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Enclosing_Operation", propOrder = {
    "overriddenFixedPriority",
    "overriddenPermanentFP",
    "operationList"
})
public class EnclosingOperation {

    @XmlElement(name = "Overridden_Fixed_Priority")
    protected OverriddenFixedPriority overriddenFixedPriority;
    @XmlElement(name = "Overridden_Permanent_FP")
    protected OverriddenPermanentFP overriddenPermanentFP;
    @XmlList
    @XmlElement(name = "Operation_List", required = true)
    protected List<String> operationList;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "Worst_Case_Execution_Time")
    protected Double worstCaseExecutionTime;
    @XmlAttribute(name = "Average_Case_Execution_Time")
    protected Double averageCaseExecutionTime;
    @XmlAttribute(name = "Best_Case_Execution_Time")
    protected Double bestCaseExecutionTime;

    /**
     * Gets the value of the overriddenFixedPriority property.
     * 
     * @return
     *     possible object is
     *     {@link OverriddenFixedPriority }
     *     
     */
    public OverriddenFixedPriority getOverriddenFixedPriority() {
        return overriddenFixedPriority;
    }

    /**
     * Sets the value of the overriddenFixedPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverriddenFixedPriority }
     *     
     */
    public void setOverriddenFixedPriority(OverriddenFixedPriority value) {
        this.overriddenFixedPriority = value;
    }

    /**
     * Gets the value of the overriddenPermanentFP property.
     * 
     * @return
     *     possible object is
     *     {@link OverriddenPermanentFP }
     *     
     */
    public OverriddenPermanentFP getOverriddenPermanentFP() {
        return overriddenPermanentFP;
    }

    /**
     * Sets the value of the overriddenPermanentFP property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverriddenPermanentFP }
     *     
     */
    public void setOverriddenPermanentFP(OverriddenPermanentFP value) {
        this.overriddenPermanentFP = value;
    }

    /**
     * Gets the value of the operationList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOperationList() {
        if (operationList == null) {
            operationList = new ArrayList<String>();
        }
        return this.operationList;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the worstCaseExecutionTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWorstCaseExecutionTime() {
        return worstCaseExecutionTime;
    }

    /**
     * Sets the value of the worstCaseExecutionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWorstCaseExecutionTime(Double value) {
        this.worstCaseExecutionTime = value;
    }

    /**
     * Gets the value of the averageCaseExecutionTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAverageCaseExecutionTime() {
        return averageCaseExecutionTime;
    }

    /**
     * Sets the value of the averageCaseExecutionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAverageCaseExecutionTime(Double value) {
        this.averageCaseExecutionTime = value;
    }

    /**
     * Gets the value of the bestCaseExecutionTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBestCaseExecutionTime() {
        return bestCaseExecutionTime;
    }

    /**
     * Sets the value of the bestCaseExecutionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBestCaseExecutionTime(Double value) {
        this.bestCaseExecutionTime = value;
    }

}
