//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Fixed_Priority_Scheduler complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fixed_Priority_Scheduler">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Worst_Context_Switch" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Avg_Context_Switch" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Best_Context_Switch" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Max_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Priority" />
 *       &lt;attribute name="Min_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Priority" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fixed_Priority_Scheduler")
public class FixedPriorityScheduler {

    @XmlAttribute(name = "Worst_Context_Switch")
    protected Double worstContextSwitch;
    @XmlAttribute(name = "Avg_Context_Switch")
    protected Double avgContextSwitch;
    @XmlAttribute(name = "Best_Context_Switch")
    protected Double bestContextSwitch;
    @XmlAttribute(name = "Max_Priority")
    protected BigInteger maxPriority;
    @XmlAttribute(name = "Min_Priority")
    protected BigInteger minPriority;

    /**
     * Gets the value of the worstContextSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWorstContextSwitch() {
        return worstContextSwitch;
    }

    /**
     * Sets the value of the worstContextSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWorstContextSwitch(Double value) {
        this.worstContextSwitch = value;
    }

    /**
     * Gets the value of the avgContextSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvgContextSwitch() {
        return avgContextSwitch;
    }

    /**
     * Sets the value of the avgContextSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvgContextSwitch(Double value) {
        this.avgContextSwitch = value;
    }

    /**
     * Gets the value of the bestContextSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBestContextSwitch() {
        return bestContextSwitch;
    }

    /**
     * Sets the value of the bestContextSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBestContextSwitch(Double value) {
        this.bestContextSwitch = value;
    }

    /**
     * Gets the value of the maxPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxPriority() {
        return maxPriority;
    }

    /**
     * Sets the value of the maxPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxPriority(BigInteger value) {
        this.maxPriority = value;
    }

    /**
     * Gets the value of the minPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinPriority() {
        return minPriority;
    }

    /**
     * Sets the value of the minPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinPriority(BigInteger value) {
        this.minPriority = value;
    }

}
