//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FP_Packet_Based_Scheduler complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FP_Packet_Based_Scheduler">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Max_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Priority" />
 *       &lt;attribute name="Min_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Priority" />
 *       &lt;attribute name="Packet_Overhead_Max_Size" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Bit_Count" />
 *       &lt;attribute name="Packet_Overhead_Min_Size" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Bit_Count" />
 *       &lt;attribute name="Packet_Overhead_Avg_Size" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Bit_Count" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FP_Packet_Based_Scheduler")
public class FPPacketBasedScheduler {

    @XmlAttribute(name = "Max_Priority")
    protected BigInteger maxPriority;
    @XmlAttribute(name = "Min_Priority")
    protected BigInteger minPriority;
    @XmlAttribute(name = "Packet_Overhead_Max_Size")
    protected Float packetOverheadMaxSize;
    @XmlAttribute(name = "Packet_Overhead_Min_Size")
    protected Float packetOverheadMinSize;
    @XmlAttribute(name = "Packet_Overhead_Avg_Size")
    protected Float packetOverheadAvgSize;

    /**
     * Gets the value of the maxPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxPriority() {
        return maxPriority;
    }

    /**
     * Sets the value of the maxPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxPriority(BigInteger value) {
        this.maxPriority = value;
    }

    /**
     * Gets the value of the minPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinPriority() {
        return minPriority;
    }

    /**
     * Sets the value of the minPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinPriority(BigInteger value) {
        this.minPriority = value;
    }

    /**
     * Gets the value of the packetOverheadMaxSize property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPacketOverheadMaxSize() {
        return packetOverheadMaxSize;
    }

    /**
     * Sets the value of the packetOverheadMaxSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPacketOverheadMaxSize(Float value) {
        this.packetOverheadMaxSize = value;
    }

    /**
     * Gets the value of the packetOverheadMinSize property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPacketOverheadMinSize() {
        return packetOverheadMinSize;
    }

    /**
     * Sets the value of the packetOverheadMinSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPacketOverheadMinSize(Float value) {
        this.packetOverheadMinSize = value;
    }

    /**
     * Gets the value of the packetOverheadAvgSize property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPacketOverheadAvgSize() {
        return packetOverheadAvgSize;
    }

    /**
     * Sets the value of the packetOverheadAvgSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPacketOverheadAvgSize(Float value) {
        this.packetOverheadAvgSize = value;
    }

}
