//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Regular_Processor" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Regular_Processor"/>
 *         &lt;element name="Packet_Based_Network" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Packet_Based_Network"/>
 *         &lt;element name="Primary_Scheduler" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Primary_Scheduler"/>
 *         &lt;element name="Secondary_Scheduler" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Secondary_Scheduler"/>
 *         &lt;element name="Regular_Scheduling_Server" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Regular_Scheduling_Server"/>
 *         &lt;element name="Immediate_Ceiling_Resource" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Immediate_Ceiling_Resource"/>
 *         &lt;element name="Priority_Inheritance_Resource" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Priority_Inheritance_Resource"/>
 *         &lt;element name="SRP_Resource" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}SRP_Resource"/>
 *         &lt;element name="Simple_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Simple_Operation"/>
 *         &lt;element name="Composite_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Composite_Operation"/>
 *         &lt;element name="Enclosing_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Enclosing_Operation"/>
 *         &lt;element name="Message_Transmission" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Message_Transmission"/>
 *         &lt;element name="Regular_Transaction" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Regular_Transaction"/>
 *       &lt;/choice>
 *       &lt;attribute name="Model_Name" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier" />
 *       &lt;attribute name="Model_Date" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Date_Time" />
 *       &lt;attribute name="System_PiP_Behaviour" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Priority_Inheritance_Protocol" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "regularProcessorOrPacketBasedNetworkOrPrimaryScheduler"
})
@XmlRootElement(name = "MAST_MODEL")
public class MASTMODEL {

    @XmlElements({
        @XmlElement(name = "Regular_Processor", type = RegularProcessor.class),
        @XmlElement(name = "Packet_Based_Network", type = PacketBasedNetwork.class),
        @XmlElement(name = "Primary_Scheduler", type = PrimaryScheduler.class),
        @XmlElement(name = "Secondary_Scheduler", type = SecondaryScheduler.class),
        @XmlElement(name = "Regular_Scheduling_Server", type = RegularSchedulingServer.class),
        @XmlElement(name = "Immediate_Ceiling_Resource", type = ImmediateCeilingResource.class),
        @XmlElement(name = "Priority_Inheritance_Resource", type = PriorityInheritanceResource.class),
        @XmlElement(name = "SRP_Resource", type = SRPResource.class),
        @XmlElement(name = "Simple_Operation", type = SimpleOperation.class),
        @XmlElement(name = "Composite_Operation", type = CompositeOperation.class),
        @XmlElement(name = "Enclosing_Operation", type = EnclosingOperation.class),
        @XmlElement(name = "Message_Transmission", type = MessageTransmission.class),
        @XmlElement(name = "Regular_Transaction", type = RegularTransaction.class)
    })
    protected List<Object> regularProcessorOrPacketBasedNetworkOrPrimaryScheduler;
    @XmlAttribute(name = "Model_Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String modelName;
    @XmlAttribute(name = "Model_Date", required = true)
    protected XMLGregorianCalendar modelDate;
    @XmlAttribute(name = "System_PiP_Behaviour")
    protected PriorityInheritanceProtocol systemPiPBehaviour;

    /**
     * Gets the value of the regularProcessorOrPacketBasedNetworkOrPrimaryScheduler property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regularProcessorOrPacketBasedNetworkOrPrimaryScheduler property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegularProcessorOrPacketBasedNetworkOrPrimaryScheduler().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegularProcessor }
     * {@link PacketBasedNetwork }
     * {@link PrimaryScheduler }
     * {@link SecondaryScheduler }
     * {@link RegularSchedulingServer }
     * {@link ImmediateCeilingResource }
     * {@link PriorityInheritanceResource }
     * {@link SRPResource }
     * {@link SimpleOperation }
     * {@link CompositeOperation }
     * {@link EnclosingOperation }
     * {@link MessageTransmission }
     * {@link RegularTransaction }
     * 
     * 
     */
    public List<Object> getRegularProcessorOrPacketBasedNetworkOrPrimaryScheduler() {
        if (regularProcessorOrPacketBasedNetworkOrPrimaryScheduler == null) {
            regularProcessorOrPacketBasedNetworkOrPrimaryScheduler = new ArrayList<Object>();
        }
        return this.regularProcessorOrPacketBasedNetworkOrPrimaryScheduler;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the modelDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModelDate() {
        return modelDate;
    }

    /**
     * Sets the value of the modelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModelDate(XMLGregorianCalendar value) {
        this.modelDate = value;
    }

    /**
     * Gets the value of the systemPiPBehaviour property.
     * 
     * @return
     *     possible object is
     *     {@link PriorityInheritanceProtocol }
     *     
     */
    public PriorityInheritanceProtocol getSystemPiPBehaviour() {
        return systemPiPBehaviour;
    }

    /**
     * Sets the value of the systemPiPBehaviour property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorityInheritanceProtocol }
     *     
     */
    public void setSystemPiPBehaviour(PriorityInheritanceProtocol value) {
        this.systemPiPBehaviour = value;
    }

}
