//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Message_Transmission complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message_Transmission">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="Overridden_Fixed_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Overridden_Fixed_Priority"/>
 *         &lt;element name="Overridden_Permanent_FP" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Overridden_Permanent_FP"/>
 *       &lt;/choice>
 *       &lt;attribute name="Name" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier" />
 *       &lt;attribute name="Max_Message_Size" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Bit_Count" />
 *       &lt;attribute name="Avg_Message_Size" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Bit_Count" />
 *       &lt;attribute name="Min_Message_Size" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Bit_Count" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message_Transmission", propOrder = {
    "overriddenFixedPriority",
    "overriddenPermanentFP"
})
public class MessageTransmission {

    @XmlElement(name = "Overridden_Fixed_Priority")
    protected OverriddenFixedPriority overriddenFixedPriority;
    @XmlElement(name = "Overridden_Permanent_FP")
    protected OverriddenPermanentFP overriddenPermanentFP;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "Max_Message_Size")
    protected Float maxMessageSize;
    @XmlAttribute(name = "Avg_Message_Size")
    protected Float avgMessageSize;
    @XmlAttribute(name = "Min_Message_Size")
    protected Float minMessageSize;

    /**
     * Gets the value of the overriddenFixedPriority property.
     * 
     * @return
     *     possible object is
     *     {@link OverriddenFixedPriority }
     *     
     */
    public OverriddenFixedPriority getOverriddenFixedPriority() {
        return overriddenFixedPriority;
    }

    /**
     * Sets the value of the overriddenFixedPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverriddenFixedPriority }
     *     
     */
    public void setOverriddenFixedPriority(OverriddenFixedPriority value) {
        this.overriddenFixedPriority = value;
    }

    /**
     * Gets the value of the overriddenPermanentFP property.
     * 
     * @return
     *     possible object is
     *     {@link OverriddenPermanentFP }
     *     
     */
    public OverriddenPermanentFP getOverriddenPermanentFP() {
        return overriddenPermanentFP;
    }

    /**
     * Sets the value of the overriddenPermanentFP property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverriddenPermanentFP }
     *     
     */
    public void setOverriddenPermanentFP(OverriddenPermanentFP value) {
        this.overriddenPermanentFP = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the maxMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaxMessageSize() {
        return maxMessageSize;
    }

    /**
     * Sets the value of the maxMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaxMessageSize(Float value) {
        this.maxMessageSize = value;
    }

    /**
     * Gets the value of the avgMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAvgMessageSize() {
        return avgMessageSize;
    }

    /**
     * Sets the value of the avgMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAvgMessageSize(Float value) {
        this.avgMessageSize = value;
    }

    /**
     * Gets the value of the minMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinMessageSize() {
        return minMessageSize;
    }

    /**
     * Sets the value of the minMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinMessageSize(Float value) {
        this.minMessageSize = value;
    }

}
