//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Negative_Assertion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Negative_Assertion">
 *   &lt;restriction base="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Assertion">
 *     &lt;enumeration value="NO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Negative_Assertion")
@XmlEnum(Assertion.class)
public enum NegativeAssertion {

    NO;

    public String value() {
        return name();
    }

    public static NegativeAssertion fromValue(String v) {
        return valueOf(v);
    }

}
