//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.unican.mast.xmlmast.xmlmast_1_4.mast_model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.unican.mast.xmlmast.xmlmast_1_4.mast_model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MASTMODEL }
     * 
     */
    public MASTMODEL createMASTMODEL() {
        return new MASTMODEL();
    }

    /**
     * Create an instance of {@link RegularProcessor }
     * 
     */
    public RegularProcessor createRegularProcessor() {
        return new RegularProcessor();
    }

    /**
     * Create an instance of {@link PacketBasedNetwork }
     * 
     */
    public PacketBasedNetwork createPacketBasedNetwork() {
        return new PacketBasedNetwork();
    }

    /**
     * Create an instance of {@link PrimaryScheduler }
     * 
     */
    public PrimaryScheduler createPrimaryScheduler() {
        return new PrimaryScheduler();
    }

    /**
     * Create an instance of {@link SecondaryScheduler }
     * 
     */
    public SecondaryScheduler createSecondaryScheduler() {
        return new SecondaryScheduler();
    }

    /**
     * Create an instance of {@link RegularSchedulingServer }
     * 
     */
    public RegularSchedulingServer createRegularSchedulingServer() {
        return new RegularSchedulingServer();
    }

    /**
     * Create an instance of {@link ImmediateCeilingResource }
     * 
     */
    public ImmediateCeilingResource createImmediateCeilingResource() {
        return new ImmediateCeilingResource();
    }

    /**
     * Create an instance of {@link PriorityInheritanceResource }
     * 
     */
    public PriorityInheritanceResource createPriorityInheritanceResource() {
        return new PriorityInheritanceResource();
    }

    /**
     * Create an instance of {@link SRPResource }
     * 
     */
    public SRPResource createSRPResource() {
        return new SRPResource();
    }

    /**
     * Create an instance of {@link SimpleOperation }
     * 
     */
    public SimpleOperation createSimpleOperation() {
        return new SimpleOperation();
    }

    /**
     * Create an instance of {@link CompositeOperation }
     * 
     */
    public CompositeOperation createCompositeOperation() {
        return new CompositeOperation();
    }

    /**
     * Create an instance of {@link EnclosingOperation }
     * 
     */
    public EnclosingOperation createEnclosingOperation() {
        return new EnclosingOperation();
    }

    /**
     * Create an instance of {@link MessageTransmission }
     * 
     */
    public MessageTransmission createMessageTransmission() {
        return new MessageTransmission();
    }

    /**
     * Create an instance of {@link RegularTransaction }
     * 
     */
    public RegularTransaction createRegularTransaction() {
        return new RegularTransaction();
    }

    /**
     * Create an instance of {@link UnboundedExternalEvent }
     * 
     */
    public UnboundedExternalEvent createUnboundedExternalEvent() {
        return new UnboundedExternalEvent();
    }

    /**
     * Create an instance of {@link OverriddenPermanentFP }
     * 
     */
    public OverriddenPermanentFP createOverriddenPermanentFP() {
        return new OverriddenPermanentFP();
    }

    /**
     * Create an instance of {@link SporadicServerPolicy }
     * 
     */
    public SporadicServerPolicy createSporadicServerPolicy() {
        return new SporadicServerPolicy();
    }

    /**
     * Create an instance of {@link Offset }
     * 
     */
    public Offset createOffset() {
        return new Offset();
    }

    /**
     * Create an instance of {@link TickerSystemTimer }
     * 
     */
    public TickerSystemTimer createTickerSystemTimer() {
        return new TickerSystemTimer();
    }

    /**
     * Create an instance of {@link PacketDriver }
     * 
     */
    public PacketDriver createPacketDriver() {
        return new PacketDriver();
    }

    /**
     * Create an instance of {@link Barrier }
     * 
     */
    public Barrier createBarrier() {
        return new Barrier();
    }

    /**
     * Create an instance of {@link DeliveryServer }
     * 
     */
    public DeliveryServer createDeliveryServer() {
        return new DeliveryServer();
    }

    /**
     * Create an instance of {@link Delay }
     * 
     */
    public Delay createDelay() {
        return new Delay();
    }

    /**
     * Create an instance of {@link Multicast }
     * 
     */
    public Multicast createMulticast() {
        return new Multicast();
    }

    /**
     * Create an instance of {@link EDFScheduler }
     * 
     */
    public EDFScheduler createEDFScheduler() {
        return new EDFScheduler();
    }

    /**
     * Create an instance of {@link RTEPPacketDriver }
     * 
     */
    public RTEPPacketDriver createRTEPPacketDriver() {
        return new RTEPPacketDriver();
    }

    /**
     * Create an instance of {@link ListOfDrivers }
     * 
     */
    public ListOfDrivers createListOfDrivers() {
        return new ListOfDrivers();
    }

    /**
     * Create an instance of {@link NonPreemptibleFPPolicy }
     * 
     */
    public NonPreemptibleFPPolicy createNonPreemptibleFPPolicy() {
        return new NonPreemptibleFPPolicy();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link SoftLocalDeadline }
     * 
     */
    public SoftLocalDeadline createSoftLocalDeadline() {
        return new SoftLocalDeadline();
    }

    /**
     * Create an instance of {@link RateDivisor }
     * 
     */
    public RateDivisor createRateDivisor() {
        return new RateDivisor();
    }

    /**
     * Create an instance of {@link RegularEvent }
     * 
     */
    public RegularEvent createRegularEvent() {
        return new RegularEvent();
    }

    /**
     * Create an instance of {@link HardGlobalDeadline }
     * 
     */
    public HardGlobalDeadline createHardGlobalDeadline() {
        return new HardGlobalDeadline();
    }

    /**
     * Create an instance of {@link EDFPolicy }
     * 
     */
    public EDFPolicy createEDFPolicy() {
        return new EDFPolicy();
    }

    /**
     * Create an instance of {@link SporadicExternalEvent }
     * 
     */
    public SporadicExternalEvent createSporadicExternalEvent() {
        return new SporadicExternalEvent();
    }

    /**
     * Create an instance of {@link SingularExternalEvent }
     * 
     */
    public SingularExternalEvent createSingularExternalEvent() {
        return new SingularExternalEvent();
    }

    /**
     * Create an instance of {@link PeriodicExternalEvent }
     * 
     */
    public PeriodicExternalEvent createPeriodicExternalEvent() {
        return new PeriodicExternalEvent();
    }

    /**
     * Create an instance of {@link PollingPolicy }
     * 
     */
    public PollingPolicy createPollingPolicy() {
        return new PollingPolicy();
    }

    /**
     * Create an instance of {@link GlobalMaxMissRatio }
     * 
     */
    public GlobalMaxMissRatio createGlobalMaxMissRatio() {
        return new GlobalMaxMissRatio();
    }

    /**
     * Create an instance of {@link AlarmClockSystemTimer }
     * 
     */
    public AlarmClockSystemTimer createAlarmClockSystemTimer() {
        return new AlarmClockSystemTimer();
    }

    /**
     * Create an instance of {@link CompositeTimingRequirement }
     * 
     */
    public CompositeTimingRequirement createCompositeTimingRequirement() {
        return new CompositeTimingRequirement();
    }

    /**
     * Create an instance of {@link Concentrator }
     * 
     */
    public Concentrator createConcentrator() {
        return new Concentrator();
    }

    /**
     * Create an instance of {@link HardLocalDeadline }
     * 
     */
    public HardLocalDeadline createHardLocalDeadline() {
        return new HardLocalDeadline();
    }

    /**
     * Create an instance of {@link SoftGlobalDeadline }
     * 
     */
    public SoftGlobalDeadline createSoftGlobalDeadline() {
        return new SoftGlobalDeadline();
    }

    /**
     * Create an instance of {@link OverriddenFixedPriority }
     * 
     */
    public OverriddenFixedPriority createOverriddenFixedPriority() {
        return new OverriddenFixedPriority();
    }

    /**
     * Create an instance of {@link MaxOutputJitterReq }
     * 
     */
    public MaxOutputJitterReq createMaxOutputJitterReq() {
        return new MaxOutputJitterReq();
    }

    /**
     * Create an instance of {@link CharacterPacketDriver }
     * 
     */
    public CharacterPacketDriver createCharacterPacketDriver() {
        return new CharacterPacketDriver();
    }

    /**
     * Create an instance of {@link FixedPriorityPolicy }
     * 
     */
    public FixedPriorityPolicy createFixedPriorityPolicy() {
        return new FixedPriorityPolicy();
    }

    /**
     * Create an instance of {@link BurstyExternalEvent }
     * 
     */
    public BurstyExternalEvent createBurstyExternalEvent() {
        return new BurstyExternalEvent();
    }

    /**
     * Create an instance of {@link SRPParameters }
     * 
     */
    public SRPParameters createSRPParameters() {
        return new SRPParameters();
    }

    /**
     * Create an instance of {@link QueryServer }
     * 
     */
    public QueryServer createQueryServer() {
        return new QueryServer();
    }

    /**
     * Create an instance of {@link FixedPriorityScheduler }
     * 
     */
    public FixedPriorityScheduler createFixedPriorityScheduler() {
        return new FixedPriorityScheduler();
    }

    /**
     * Create an instance of {@link SystemTimedActivity }
     * 
     */
    public SystemTimedActivity createSystemTimedActivity() {
        return new SystemTimedActivity();
    }

    /**
     * Create an instance of {@link LocalMaxMissRatio }
     * 
     */
    public LocalMaxMissRatio createLocalMaxMissRatio() {
        return new LocalMaxMissRatio();
    }

    /**
     * Create an instance of {@link FPPacketBasedScheduler }
     * 
     */
    public FPPacketBasedScheduler createFPPacketBasedScheduler() {
        return new FPPacketBasedScheduler();
    }

    /**
     * Create an instance of {@link InterruptFPPolicy }
     * 
     */
    public InterruptFPPolicy createInterruptFPPolicy() {
        return new InterruptFPPolicy();
    }

}
