//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Packet_Based_Network complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Packet_Based_Network">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="List_of_Drivers" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}List_of_Drivers" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier" />
 *       &lt;attribute name="Speed_Factor" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Float" />
 *       &lt;attribute name="Throughput" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Throughput" />
 *       &lt;attribute name="Transmission" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Transmission_Type" />
 *       &lt;attribute name="Max_Blocking" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Max_Packet_Size" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Bit_Count" />
 *       &lt;attribute name="Min_Packet_Size" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Bit_Count" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Packet_Based_Network", propOrder = {
    "listOfDrivers"
})
public class PacketBasedNetwork {

    @XmlElement(name = "List_of_Drivers")
    protected ListOfDrivers listOfDrivers;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "Speed_Factor")
    protected Float speedFactor;
    @XmlAttribute(name = "Throughput")
    protected Float throughput;
    @XmlAttribute(name = "Transmission")
    protected TransmissionType transmission;
    @XmlAttribute(name = "Max_Blocking")
    protected Double maxBlocking;
    @XmlAttribute(name = "Max_Packet_Size")
    protected Float maxPacketSize;
    @XmlAttribute(name = "Min_Packet_Size")
    protected Float minPacketSize;

    /**
     * Gets the value of the listOfDrivers property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfDrivers }
     *     
     */
    public ListOfDrivers getListOfDrivers() {
        return listOfDrivers;
    }

    /**
     * Sets the value of the listOfDrivers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfDrivers }
     *     
     */
    public void setListOfDrivers(ListOfDrivers value) {
        this.listOfDrivers = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the speedFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSpeedFactor() {
        return speedFactor;
    }

    /**
     * Sets the value of the speedFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSpeedFactor(Float value) {
        this.speedFactor = value;
    }

    /**
     * Gets the value of the throughput property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getThroughput() {
        return throughput;
    }

    /**
     * Sets the value of the throughput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setThroughput(Float value) {
        this.throughput = value;
    }

    /**
     * Gets the value of the transmission property.
     * 
     * @return
     *     possible object is
     *     {@link TransmissionType }
     *     
     */
    public TransmissionType getTransmission() {
        return transmission;
    }

    /**
     * Sets the value of the transmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmissionType }
     *     
     */
    public void setTransmission(TransmissionType value) {
        this.transmission = value;
    }

    /**
     * Gets the value of the maxBlocking property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxBlocking() {
        return maxBlocking;
    }

    /**
     * Sets the value of the maxBlocking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxBlocking(Double value) {
        this.maxBlocking = value;
    }

    /**
     * Gets the value of the maxPacketSize property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaxPacketSize() {
        return maxPacketSize;
    }

    /**
     * Sets the value of the maxPacketSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaxPacketSize(Float value) {
        this.maxPacketSize = value;
    }

    /**
     * Gets the value of the minPacketSize property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinPacketSize() {
        return minPacketSize;
    }

    /**
     * Sets the value of the minPacketSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinPacketSize(Float value) {
        this.minPacketSize = value;
    }

}
