//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Primary_Scheduler complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Primary_Scheduler">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="Fixed_Priority_Scheduler" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Fixed_Priority_Scheduler"/>
 *         &lt;element name="EDF_Scheduler" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}EDF_Scheduler"/>
 *         &lt;element name="FP_Packet_Based_Scheduler" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}FP_Packet_Based_Scheduler"/>
 *       &lt;/choice>
 *       &lt;attribute name="Name" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier" />
 *       &lt;attribute name="Host" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Primary_Scheduler", propOrder = {
    "fixedPriorityScheduler",
    "edfScheduler",
    "fpPacketBasedScheduler"
})
public class PrimaryScheduler {

    @XmlElement(name = "Fixed_Priority_Scheduler")
    protected FixedPriorityScheduler fixedPriorityScheduler;
    @XmlElement(name = "EDF_Scheduler")
    protected EDFScheduler edfScheduler;
    @XmlElement(name = "FP_Packet_Based_Scheduler")
    protected FPPacketBasedScheduler fpPacketBasedScheduler;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "Host", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String host;

    /**
     * Gets the value of the fixedPriorityScheduler property.
     * 
     * @return
     *     possible object is
     *     {@link FixedPriorityScheduler }
     *     
     */
    public FixedPriorityScheduler getFixedPriorityScheduler() {
        return fixedPriorityScheduler;
    }

    /**
     * Sets the value of the fixedPriorityScheduler property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixedPriorityScheduler }
     *     
     */
    public void setFixedPriorityScheduler(FixedPriorityScheduler value) {
        this.fixedPriorityScheduler = value;
    }

    /**
     * Gets the value of the edfScheduler property.
     * 
     * @return
     *     possible object is
     *     {@link EDFScheduler }
     *     
     */
    public EDFScheduler getEDFScheduler() {
        return edfScheduler;
    }

    /**
     * Sets the value of the edfScheduler property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDFScheduler }
     *     
     */
    public void setEDFScheduler(EDFScheduler value) {
        this.edfScheduler = value;
    }

    /**
     * Gets the value of the fpPacketBasedScheduler property.
     * 
     * @return
     *     possible object is
     *     {@link FPPacketBasedScheduler }
     *     
     */
    public FPPacketBasedScheduler getFPPacketBasedScheduler() {
        return fpPacketBasedScheduler;
    }

    /**
     * Sets the value of the fpPacketBasedScheduler property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPPacketBasedScheduler }
     *     
     */
    public void setFPPacketBasedScheduler(FPPacketBasedScheduler value) {
        this.fpPacketBasedScheduler = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

}
