//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Query_Server complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Query_Server">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Input_Event" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Output_Events_List" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref_List" />
 *       &lt;attribute name="Request_Policy" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Request_Policy" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Query_Server")
public class QueryServer {

    @XmlAttribute(name = "Input_Event", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inputEvent;
    @XmlAttribute(name = "Output_Events_List", required = true)
    protected List<String> outputEventsList;
    @XmlAttribute(name = "Request_Policy")
    protected RequestPolicy requestPolicy;

    /**
     * Gets the value of the inputEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputEvent() {
        return inputEvent;
    }

    /**
     * Sets the value of the inputEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputEvent(String value) {
        this.inputEvent = value;
    }

    /**
     * Gets the value of the outputEventsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputEventsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputEventsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOutputEventsList() {
        if (outputEventsList == null) {
            outputEventsList = new ArrayList<String>();
        }
        return this.outputEventsList;
    }

    /**
     * Gets the value of the requestPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link RequestPolicy }
     *     
     */
    public RequestPolicy getRequestPolicy() {
        return requestPolicy;
    }

    /**
     * Sets the value of the requestPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestPolicy }
     *     
     */
    public void setRequestPolicy(RequestPolicy value) {
        this.requestPolicy = value;
    }

}
