//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Regular_Transaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Regular_Transaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Periodic_External_Event" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Periodic_External_Event"/>
 *         &lt;element name="Sporadic_External_Event" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Sporadic_External_Event"/>
 *         &lt;element name="Unbounded_External_Event" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Unbounded_External_Event"/>
 *         &lt;element name="Bursty_External_Event" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Bursty_External_Event"/>
 *         &lt;element name="Singular_External_Event" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Singular_External_Event"/>
 *         &lt;element name="Regular_Event" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Regular_Event"/>
 *         &lt;element name="Activity" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Activity"/>
 *         &lt;element name="System_Timed_Activity" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}System_Timed_Activity"/>
 *         &lt;element name="Concentrator" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Concentrator"/>
 *         &lt;element name="Barrier" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Barrier"/>
 *         &lt;element name="Delivery_Server" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Delivery_Server"/>
 *         &lt;element name="Query_Server" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Query_Server"/>
 *         &lt;element name="Multicast" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Multicast"/>
 *         &lt;element name="Rate_Divisor" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Rate_Divisor"/>
 *         &lt;element name="Delay" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Delay"/>
 *         &lt;element name="Offset" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Offset"/>
 *       &lt;/choice>
 *       &lt;attribute name="Name" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Regular_Transaction", propOrder = {
    "periodicExternalEventOrSporadicExternalEventOrUnboundedExternalEvent"
})
public class RegularTransaction {

    @XmlElements({
        @XmlElement(name = "Periodic_External_Event", type = PeriodicExternalEvent.class),
        @XmlElement(name = "Sporadic_External_Event", type = SporadicExternalEvent.class),
        @XmlElement(name = "Unbounded_External_Event", type = UnboundedExternalEvent.class),
        @XmlElement(name = "Bursty_External_Event", type = BurstyExternalEvent.class),
        @XmlElement(name = "Singular_External_Event", type = SingularExternalEvent.class),
        @XmlElement(name = "Regular_Event", type = RegularEvent.class),
        @XmlElement(name = "Activity", type = Activity.class),
        @XmlElement(name = "System_Timed_Activity", type = SystemTimedActivity.class),
        @XmlElement(name = "Concentrator", type = Concentrator.class),
        @XmlElement(name = "Barrier", type = Barrier.class),
        @XmlElement(name = "Delivery_Server", type = DeliveryServer.class),
        @XmlElement(name = "Query_Server", type = QueryServer.class),
        @XmlElement(name = "Multicast", type = Multicast.class),
        @XmlElement(name = "Rate_Divisor", type = RateDivisor.class),
        @XmlElement(name = "Delay", type = Delay.class),
        @XmlElement(name = "Offset", type = Offset.class)
    })
    protected List<Object> periodicExternalEventOrSporadicExternalEventOrUnboundedExternalEvent;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;

    /**
     * Gets the value of the periodicExternalEventOrSporadicExternalEventOrUnboundedExternalEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodicExternalEventOrSporadicExternalEventOrUnboundedExternalEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodicExternalEventOrSporadicExternalEventOrUnboundedExternalEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeriodicExternalEvent }
     * {@link SporadicExternalEvent }
     * {@link UnboundedExternalEvent }
     * {@link BurstyExternalEvent }
     * {@link SingularExternalEvent }
     * {@link RegularEvent }
     * {@link Activity }
     * {@link SystemTimedActivity }
     * {@link Concentrator }
     * {@link Barrier }
     * {@link DeliveryServer }
     * {@link QueryServer }
     * {@link Multicast }
     * {@link RateDivisor }
     * {@link Delay }
     * {@link Offset }
     * 
     * 
     */
    public List<Object> getPeriodicExternalEventOrSporadicExternalEventOrUnboundedExternalEvent() {
        if (periodicExternalEventOrSporadicExternalEventOrUnboundedExternalEvent == null) {
            periodicExternalEventOrSporadicExternalEventOrUnboundedExternalEvent = new ArrayList<Object>();
        }
        return this.periodicExternalEventOrSporadicExternalEventOrUnboundedExternalEvent;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
