//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Regular_Processor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Regular_Processor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="Ticker_System_Timer" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Ticker_System_Timer"/>
 *         &lt;element name="Alarm_Clock_System_Timer" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Alarm_Clock_System_Timer"/>
 *       &lt;/choice>
 *       &lt;attribute name="Name" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier" />
 *       &lt;attribute name="Speed_Factor" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Float" />
 *       &lt;attribute name="Max_Interrupt_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Interrupt_Priority" />
 *       &lt;attribute name="Min_Interrupt_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Interrupt_Priority" />
 *       &lt;attribute name="Worst_ISR_Switch" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Avg_ISR_Switch" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Best_ISR_Switch" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Regular_Processor", propOrder = {
    "tickerSystemTimer",
    "alarmClockSystemTimer"
})
public class RegularProcessor {

    @XmlElement(name = "Ticker_System_Timer")
    protected TickerSystemTimer tickerSystemTimer;
    @XmlElement(name = "Alarm_Clock_System_Timer")
    protected AlarmClockSystemTimer alarmClockSystemTimer;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "Speed_Factor")
    protected Float speedFactor;
    @XmlAttribute(name = "Max_Interrupt_Priority")
    protected BigInteger maxInterruptPriority;
    @XmlAttribute(name = "Min_Interrupt_Priority")
    protected BigInteger minInterruptPriority;
    @XmlAttribute(name = "Worst_ISR_Switch")
    protected Double worstISRSwitch;
    @XmlAttribute(name = "Avg_ISR_Switch")
    protected Double avgISRSwitch;
    @XmlAttribute(name = "Best_ISR_Switch")
    protected Double bestISRSwitch;

    /**
     * Gets the value of the tickerSystemTimer property.
     * 
     * @return
     *     possible object is
     *     {@link TickerSystemTimer }
     *     
     */
    public TickerSystemTimer getTickerSystemTimer() {
        return tickerSystemTimer;
    }

    /**
     * Sets the value of the tickerSystemTimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TickerSystemTimer }
     *     
     */
    public void setTickerSystemTimer(TickerSystemTimer value) {
        this.tickerSystemTimer = value;
    }

    /**
     * Gets the value of the alarmClockSystemTimer property.
     * 
     * @return
     *     possible object is
     *     {@link AlarmClockSystemTimer }
     *     
     */
    public AlarmClockSystemTimer getAlarmClockSystemTimer() {
        return alarmClockSystemTimer;
    }

    /**
     * Sets the value of the alarmClockSystemTimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlarmClockSystemTimer }
     *     
     */
    public void setAlarmClockSystemTimer(AlarmClockSystemTimer value) {
        this.alarmClockSystemTimer = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the speedFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSpeedFactor() {
        return speedFactor;
    }

    /**
     * Sets the value of the speedFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSpeedFactor(Float value) {
        this.speedFactor = value;
    }

    /**
     * Gets the value of the maxInterruptPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxInterruptPriority() {
        return maxInterruptPriority;
    }

    /**
     * Sets the value of the maxInterruptPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxInterruptPriority(BigInteger value) {
        this.maxInterruptPriority = value;
    }

    /**
     * Gets the value of the minInterruptPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinInterruptPriority() {
        return minInterruptPriority;
    }

    /**
     * Sets the value of the minInterruptPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinInterruptPriority(BigInteger value) {
        this.minInterruptPriority = value;
    }

    /**
     * Gets the value of the worstISRSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWorstISRSwitch() {
        return worstISRSwitch;
    }

    /**
     * Sets the value of the worstISRSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWorstISRSwitch(Double value) {
        this.worstISRSwitch = value;
    }

    /**
     * Gets the value of the avgISRSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvgISRSwitch() {
        return avgISRSwitch;
    }

    /**
     * Sets the value of the avgISRSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvgISRSwitch(Double value) {
        this.avgISRSwitch = value;
    }

    /**
     * Gets the value of the bestISRSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBestISRSwitch() {
        return bestISRSwitch;
    }

    /**
     * Sets the value of the bestISRSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBestISRSwitch(Double value) {
        this.bestISRSwitch = value;
    }

}
