//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RTEP_Packet_Driver complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTEP_Packet_Driver">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Message_Partitioning" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Assertion" />
 *       &lt;attribute name="RTA_Overhead_Model" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Overhead_Type" />
 *       &lt;attribute name="Packet_Server" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Packet_Send_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Packet_Receive_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Number_Of_Stations" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Positive" />
 *       &lt;attribute name="Token_Delay" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Time" />
 *       &lt;attribute name="Failure_Timeout" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Time" />
 *       &lt;attribute name="Token_Transmission_Retries" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Natural" />
 *       &lt;attribute name="Packet_Transmission_Retries" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Natural" />
 *       &lt;attribute name="Packet_Interrupt_Server" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Packet_ISR_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Token_Check_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Token_Manage_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Packet_Discard_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Token_Retransmission_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *       &lt;attribute name="Packet_Retransmission_Operation" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier_Ref" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTEP_Packet_Driver")
public class RTEPPacketDriver {

    @XmlAttribute(name = "Message_Partitioning")
    protected Assertion messagePartitioning;
    @XmlAttribute(name = "RTA_Overhead_Model")
    protected OverheadType rtaOverheadModel;
    @XmlAttribute(name = "Packet_Server", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String packetServer;
    @XmlAttribute(name = "Packet_Send_Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String packetSendOperation;
    @XmlAttribute(name = "Packet_Receive_Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String packetReceiveOperation;
    @XmlAttribute(name = "Number_Of_Stations", required = true)
    protected BigInteger numberOfStations;
    @XmlAttribute(name = "Token_Delay")
    protected Double tokenDelay;
    @XmlAttribute(name = "Failure_Timeout")
    protected Double failureTimeout;
    @XmlAttribute(name = "Token_Transmission_Retries")
    protected BigInteger tokenTransmissionRetries;
    @XmlAttribute(name = "Packet_Transmission_Retries")
    protected BigInteger packetTransmissionRetries;
    @XmlAttribute(name = "Packet_Interrupt_Server")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String packetInterruptServer;
    @XmlAttribute(name = "Packet_ISR_Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String packetISROperation;
    @XmlAttribute(name = "Token_Check_Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tokenCheckOperation;
    @XmlAttribute(name = "Token_Manage_Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tokenManageOperation;
    @XmlAttribute(name = "Packet_Discard_Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String packetDiscardOperation;
    @XmlAttribute(name = "Token_Retransmission_Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tokenRetransmissionOperation;
    @XmlAttribute(name = "Packet_Retransmission_Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String packetRetransmissionOperation;

    /**
     * Gets the value of the messagePartitioning property.
     * 
     * @return
     *     possible object is
     *     {@link Assertion }
     *     
     */
    public Assertion getMessagePartitioning() {
        return messagePartitioning;
    }

    /**
     * Sets the value of the messagePartitioning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assertion }
     *     
     */
    public void setMessagePartitioning(Assertion value) {
        this.messagePartitioning = value;
    }

    /**
     * Gets the value of the rtaOverheadModel property.
     * 
     * @return
     *     possible object is
     *     {@link OverheadType }
     *     
     */
    public OverheadType getRTAOverheadModel() {
        return rtaOverheadModel;
    }

    /**
     * Sets the value of the rtaOverheadModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverheadType }
     *     
     */
    public void setRTAOverheadModel(OverheadType value) {
        this.rtaOverheadModel = value;
    }

    /**
     * Gets the value of the packetServer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacketServer() {
        return packetServer;
    }

    /**
     * Sets the value of the packetServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacketServer(String value) {
        this.packetServer = value;
    }

    /**
     * Gets the value of the packetSendOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacketSendOperation() {
        return packetSendOperation;
    }

    /**
     * Sets the value of the packetSendOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacketSendOperation(String value) {
        this.packetSendOperation = value;
    }

    /**
     * Gets the value of the packetReceiveOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacketReceiveOperation() {
        return packetReceiveOperation;
    }

    /**
     * Sets the value of the packetReceiveOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacketReceiveOperation(String value) {
        this.packetReceiveOperation = value;
    }

    /**
     * Gets the value of the numberOfStations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfStations() {
        return numberOfStations;
    }

    /**
     * Sets the value of the numberOfStations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfStations(BigInteger value) {
        this.numberOfStations = value;
    }

    /**
     * Gets the value of the tokenDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTokenDelay() {
        return tokenDelay;
    }

    /**
     * Sets the value of the tokenDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTokenDelay(Double value) {
        this.tokenDelay = value;
    }

    /**
     * Gets the value of the failureTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFailureTimeout() {
        return failureTimeout;
    }

    /**
     * Sets the value of the failureTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFailureTimeout(Double value) {
        this.failureTimeout = value;
    }

    /**
     * Gets the value of the tokenTransmissionRetries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTokenTransmissionRetries() {
        return tokenTransmissionRetries;
    }

    /**
     * Sets the value of the tokenTransmissionRetries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTokenTransmissionRetries(BigInteger value) {
        this.tokenTransmissionRetries = value;
    }

    /**
     * Gets the value of the packetTransmissionRetries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPacketTransmissionRetries() {
        return packetTransmissionRetries;
    }

    /**
     * Sets the value of the packetTransmissionRetries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPacketTransmissionRetries(BigInteger value) {
        this.packetTransmissionRetries = value;
    }

    /**
     * Gets the value of the packetInterruptServer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacketInterruptServer() {
        return packetInterruptServer;
    }

    /**
     * Sets the value of the packetInterruptServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacketInterruptServer(String value) {
        this.packetInterruptServer = value;
    }

    /**
     * Gets the value of the packetISROperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacketISROperation() {
        return packetISROperation;
    }

    /**
     * Sets the value of the packetISROperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacketISROperation(String value) {
        this.packetISROperation = value;
    }

    /**
     * Gets the value of the tokenCheckOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenCheckOperation() {
        return tokenCheckOperation;
    }

    /**
     * Sets the value of the tokenCheckOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenCheckOperation(String value) {
        this.tokenCheckOperation = value;
    }

    /**
     * Gets the value of the tokenManageOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenManageOperation() {
        return tokenManageOperation;
    }

    /**
     * Sets the value of the tokenManageOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenManageOperation(String value) {
        this.tokenManageOperation = value;
    }

    /**
     * Gets the value of the packetDiscardOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacketDiscardOperation() {
        return packetDiscardOperation;
    }

    /**
     * Sets the value of the packetDiscardOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacketDiscardOperation(String value) {
        this.packetDiscardOperation = value;
    }

    /**
     * Gets the value of the tokenRetransmissionOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenRetransmissionOperation() {
        return tokenRetransmissionOperation;
    }

    /**
     * Sets the value of the tokenRetransmissionOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenRetransmissionOperation(String value) {
        this.tokenRetransmissionOperation = value;
    }

    /**
     * Gets the value of the packetRetransmissionOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacketRetransmissionOperation() {
        return packetRetransmissionOperation;
    }

    /**
     * Sets the value of the packetRetransmissionOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacketRetransmissionOperation(String value) {
        this.packetRetransmissionOperation = value;
    }

}
