//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Sporadic_External_Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sporadic_External_Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Name" use="required" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Identifier" />
 *       &lt;attribute name="Avg_Interarrival" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Time" />
 *       &lt;attribute name="Min_Interarrival" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Time" />
 *       &lt;attribute name="Distribution" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Distribution_Type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sporadic_External_Event")
public class SporadicExternalEvent {

    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "Avg_Interarrival")
    protected Double avgInterarrival;
    @XmlAttribute(name = "Min_Interarrival")
    protected Double minInterarrival;
    @XmlAttribute(name = "Distribution")
    protected DistributionType distribution;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the avgInterarrival property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvgInterarrival() {
        return avgInterarrival;
    }

    /**
     * Sets the value of the avgInterarrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvgInterarrival(Double value) {
        this.avgInterarrival = value;
    }

    /**
     * Gets the value of the minInterarrival property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinInterarrival() {
        return minInterarrival;
    }

    /**
     * Sets the value of the minInterarrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinInterarrival(Double value) {
        this.minInterarrival = value;
    }

    /**
     * Gets the value of the distribution property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionType }
     *     
     */
    public DistributionType getDistribution() {
        return distribution;
    }

    /**
     * Sets the value of the distribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionType }
     *     
     */
    public void setDistribution(DistributionType value) {
        this.distribution = value;
    }

}
