//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sporadic_Server_Policy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sporadic_Server_Policy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Normal_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Priority" />
 *       &lt;attribute name="Preassigned" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Assertion" />
 *       &lt;attribute name="Background_Priority" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Priority" />
 *       &lt;attribute name="Initial_Capacity" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Time" />
 *       &lt;attribute name="Replenishment_Period" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Time" />
 *       &lt;attribute name="Max_Pending_Replenishments" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Positive" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sporadic_Server_Policy")
public class SporadicServerPolicy {

    @XmlAttribute(name = "Normal_Priority")
    protected BigInteger normalPriority;
    @XmlAttribute(name = "Preassigned")
    protected Assertion preassigned;
    @XmlAttribute(name = "Background_Priority")
    protected BigInteger backgroundPriority;
    @XmlAttribute(name = "Initial_Capacity")
    protected Double initialCapacity;
    @XmlAttribute(name = "Replenishment_Period")
    protected Double replenishmentPeriod;
    @XmlAttribute(name = "Max_Pending_Replenishments")
    protected BigInteger maxPendingReplenishments;

    /**
     * Gets the value of the normalPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNormalPriority() {
        return normalPriority;
    }

    /**
     * Sets the value of the normalPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNormalPriority(BigInteger value) {
        this.normalPriority = value;
    }

    /**
     * Gets the value of the preassigned property.
     * 
     * @return
     *     possible object is
     *     {@link Assertion }
     *     
     */
    public Assertion getPreassigned() {
        return preassigned;
    }

    /**
     * Sets the value of the preassigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assertion }
     *     
     */
    public void setPreassigned(Assertion value) {
        this.preassigned = value;
    }

    /**
     * Gets the value of the backgroundPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBackgroundPriority() {
        return backgroundPriority;
    }

    /**
     * Sets the value of the backgroundPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBackgroundPriority(BigInteger value) {
        this.backgroundPriority = value;
    }

    /**
     * Gets the value of the initialCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInitialCapacity() {
        return initialCapacity;
    }

    /**
     * Sets the value of the initialCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInitialCapacity(Double value) {
        this.initialCapacity = value;
    }

    /**
     * Gets the value of the replenishmentPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getReplenishmentPeriod() {
        return replenishmentPeriod;
    }

    /**
     * Sets the value of the replenishmentPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setReplenishmentPeriod(Double value) {
        this.replenishmentPeriod = value;
    }

    /**
     * Gets the value of the maxPendingReplenishments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxPendingReplenishments() {
        return maxPendingReplenishments;
    }

    /**
     * Sets the value of the maxPendingReplenishments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxPendingReplenishments(BigInteger value) {
        this.maxPendingReplenishments = value;
    }

}
