//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 01:08:01 PM CET 
//


package es.unican.istr.gen4mast.tool.xmlmodels.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ticker_System_Timer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ticker_System_Timer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Worst_Overhead" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Avg_Overhead" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Best_Overhead" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Normalized_Execution_Time" />
 *       &lt;attribute name="Period" type="{http://mast.unican.es/xmlmast/xmlmast_1_4/Mast_Model}Time" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ticker_System_Timer")
public class TickerSystemTimer {

    @XmlAttribute(name = "Worst_Overhead")
    protected Double worstOverhead;
    @XmlAttribute(name = "Avg_Overhead")
    protected Double avgOverhead;
    @XmlAttribute(name = "Best_Overhead")
    protected Double bestOverhead;
    @XmlAttribute(name = "Period")
    protected Double period;

    /**
     * Gets the value of the worstOverhead property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWorstOverhead() {
        return worstOverhead;
    }

    /**
     * Sets the value of the worstOverhead property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWorstOverhead(Double value) {
        this.worstOverhead = value;
    }

    /**
     * Gets the value of the avgOverhead property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvgOverhead() {
        return avgOverhead;
    }

    /**
     * Sets the value of the avgOverhead property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvgOverhead(Double value) {
        this.avgOverhead = value;
    }

    /**
     * Gets the value of the bestOverhead property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBestOverhead() {
        return bestOverhead;
    }

    /**
     * Sets the value of the bestOverhead property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBestOverhead(Double value) {
        this.bestOverhead = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPeriod(Double value) {
        this.period = value;
    }

}
